# Generated by Django 2.0.5 on 2018-05-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationship',
            field=models.CharField(choices=[('Wife', 'Wife'), ('Own-child', 'Own-child'), ('Husband', 'Husband'), ('Not-in-family', 'Not-in-family'), ('Other-relative', 'Other-relative'), ('Unmarried', 'Unmarried')], max_length=20, unique=True),
        ),
    ]
