# Generated by Django 2.0.5 on 2018-05-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adult', '0002_auto_20180528_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='education',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('Some-college', 'Some-college'), ('11th', '11th'), ('HS-grad', 'HS-grad'), ('Assoc-acdm', 'Assoc-acdm'), ('9th', '9th'), ('7th-8th', '7th-8th'), ('Masters', 'Masters'), ('1st-4th', '1st-4th'), ('10th', '10th'), ('Doctorate', 'Doctorate'), ('5th-6th', '5th-6th'), ('Preschool', 'Preschool')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='martialstatus',
            name='martialstatus',
            field=models.CharField(choices=[('Married-civ-spouse', 'Married-civ-spouse'), ('Divorced', 'Divorced'), ('Never-married', 'Never-married'), ('Separated', 'Separated'), ('Widowed', 'Widowed'), ('Married-spouse-absent', 'Married-spouse-absent'), ('Married-AF-spouse', 'Married-AF-spouse')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='nativecountry',
            name='nativecountry',
            field=models.CharField(choices=[('United-States', 'United-States'), ('Cambodia', 'Cambodia'), ('England', 'England'), ('Puerto-Rico', 'Puerto-Rico'), ('Canada', 'Canada'), ('Germany', 'Germany'), ('Outlying-US', 'Outlying-US(Guam-USVI-etc)'), ('India', 'India'), ('Japan', 'Japan'), ('Greece', 'Greece'), ('South', 'South'), ('China', 'China'), ('Cuba', 'Cuba'), ('Iran', 'Iran'), ('Honduras', 'Honduras'), ('Philippines', 'Philippines'), ('Italy', 'Italy'), ('Poland', 'Poland'), ('Jamaica', 'Jamaica'), ('Vietnam', 'Vietnam'), ('Mexico', 'Mexico'), ('Portugal', 'Portugal'), ('Ireland', 'Ireland'), ('France', 'France'), ('Dominican-Republic', 'Dominican-Republic'), ('Laos', 'Laos'), ('Ecuador', 'Ecuador'), ('Taiwan', 'Taiwan'), ('Haiti', 'Haiti'), ('Columbia', 'Columbia'), ('Hungary', 'Hungary'), ('Guatemala', 'Guatemala'), ('Nicaragua', 'Nicaragua'), ('Scotland', 'Scotland'), ('Thailand', 'Thailand'), ('Yugoslavia', 'Yugoslavia'), ('El-Salvador', 'El-Salvador'), ('Trinadad&Tobago', 'Trinadad&Tobago'), ('Peru', 'Peru'), ('HongKong', 'HongKong'), ('Holand-Netherlands', 'Holand-Netherlands')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='occupation',
            field=models.CharField(choices=[('Wife', 'Wife'), ('Own-child', 'Own-child'), ('Husband', 'Husband'), ('Not-in-family', 'Not-in-family'), ('Other-relative', 'Other-relative'), ('Unmarried', 'Unmarried')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='race',
            field=models.CharField(choices=[('White', 'White'), ('Asian-Pac-Islander', 'Asian-Pac-Islander'), ('Amer-Indian-Eskimo', 'Amer-Indian-Eskimo'), ('Other', 'Other'), ('Black', 'Black')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='workclass',
            name='workclass',
            field=models.CharField(choices=[('Private', 'Private'), ('Self-emp-not-inc', 'Self-emp-not-inc'), ('Self-emp-inc', 'Self-emp-inc'), ('Federal-gov', 'Federal-gov'), ('Local-gov', 'Local-gov'), ('State-gov', 'State-gov'), ('Without-pay', 'Without-pay'), ('Never-worked', 'Never-worked')], max_length=30, unique=True),
        ),
    ]
